# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_categorie_examplemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostFeaturedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
