# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170501_1624'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.RemoveField(
            model_name='postfeaturedimage',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='PostFeaturedImage',
        ),
    ]
